[tool.poetry]
name = "LLMAbstractModel"
version = "0.1.0"
description = "LLMAbstractModel"
authors = ["koki.chin <545705507@qq.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
pydantic = "^2.9.2"
requests = "^2.32.3"
numpy = "^2.3.0"

[tool.poetry.group.dev.dependencies]
ipython = "^9.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
